Revert "Bug 1221821 - Enable support for evergreen browsers"
This reverts commit 37681d6a21d626ae662bfde0e4f6643a87bedd83.

The non-transpiled files (dist/bundle) were erroring with:

ReferenceError: can't access lexical declaration `Intl' before initialization